### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mango-habanero** [SalamaTracker/traccar#1]
Draft a roadmap for a solid infrastructure implementation:

- [ ] Create Azure Resource Management (ARM) template.
- [ ] Add GitHub action workflows to deploy Traccar image on VM.
- [ ] Implement a backup strategy for the database.
- [x] Add observability tools.

Assignees: @SpencerOfwiti @PhilipWafula
